src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import NotFoundView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("core/", include("core.urls")),
    path("students/", include("students.urls")),
    path("groups/", include("groups.urls")),
    path("teachers/", include("teachers.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = NotFoundView.as_view()

src/core/urls.py
from django.urls import path

from core.views import IndexView, UserLoginView, UserLogoutView, UserRegistrationView, ActivateUser, UserProfileView

appname = "core"


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("registration/", UserRegistrationView.as_view(), name="registration"),
    path("profile/<int:pk>", UserProfileView.as_view(), name="user_profile"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
]

src/groups/urls.py
from django.contrib import admin  # NOQA
from django.urls import path

from groups.views import CreateGroupView, UpdateGroupView, DeleteGroupView, GetGroupsView, GetGroupInfoView

app_name = "groups"

urlpatterns = [
    path("", GetGroupsView.as_view(), name="groups_list"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<uuid:uuid>", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<uuid:uuid>", DeleteGroupView.as_view(), name="delete_group"),
    path("info/<uuid:uuid>", GetGroupInfoView.as_view(), name="group_info"),
]

src/teachers/urls.py
from django.urls import path

from teachers.views import CreateTeacherView, UpdateTeacherView, DeleteTeacherView, GetTeachersView

app_name = "teachers"

urlpatterns = [
    path("", GetTeachersView.as_view(), name="teachers_list"),
    path("create/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update/<uuid:uuid>", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<uuid:uuid>", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/teachers/models.py
import random

from django.db import models
from faker import Faker

from students.models import Person


class Teacher(Person):
    avatar = models.ImageField(upload_to="teachers_avatars/", null=True)
    resume = models.FileField(upload_to="teachers_resumes/", null=True)
    salary = models.IntegerField(default=0, null=True)
    groups = models.ManyToManyField(to="groups.Group", related_name="teachers")

    def __str__(self):
        return f"{self.first_name}_{self.last_name} ({self.pk})"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for _ in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                salary=random.randint(500, 2500),
                birth_day=faker.date_time_between(start_date="-30y", end_date="-18y"),
                department=faker.job(),
                group=faker.job(),
            )

src/teachers/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from teachers.models import Teacher


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = "__all__"

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_first_name(self):
        first_name = self.cleaned_data["first_name"]

        if not first_name.isalpha():
            raise ValidationError("First name mustn't contain digits!")

        return self.normalize_text(first_name)

    def clean_last_name(self):
        last_name = self.cleaned_data["last_name"]

        if not last_name.isalpha():
            raise ValidationError("Last name mustn't contain digits!")

        return self.normalize_text(last_name)

    def clean_email(self):
        email = self.cleaned_data["email"]

        if "@yandex" in email.lower():
            raise ValidationError("Yandex domain is forbidden in our country!")

        return email

    def clean(self):
        cleand_data = super().clean()

        first_name = cleand_data["first_name"]
        last_name = cleand_data["last_name"]

        if last_name == first_name:
            raise ValidationError("First name and last name can't be equal!")

        return cleand_data

src/teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from core.utils.helpers import objects_search
from teachers.forms import TeacherForm
from teachers.models import Teacher


class GetTeachersView(LoginRequiredMixin, ListView):
    template_name = "teachers/teachers_list.html"
    model = Teacher

    def get_teachers(self):
        search_fields = ["last_name", "first_name", "email"]
        return objects_search(self.request.GET, self.model, search_fields)

    def get_queryset(self):
        return self.get_teachers()


class CreateTeacherView(LoginRequiredMixin, CreateView):
    template_name = "teachers/create_teacher.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:teachers_list")


class UpdateTeacherView(LoginRequiredMixin, UpdateView):
    template_name = "teachers/update_teacher.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:teachers_list")
    pk_url_kwarg = "uuid"
    queryset = Teacher.objects.all()


class DeleteTeacherView(LoginRequiredMixin, DeleteView):
    template_name = "teachers/delete_teacher.html"
    model = Teacher
    success_url = reverse_lazy("teachers:teachers_list")
    pk_url_kwarg = "uuid"
    queryset = Teacher.objects.all()

src/templates/teachers/create_teacher.html
{% extends "core/index.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <div>
    <form method="POST" style="width: 65mm; align-content: center; margin: auto" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <br>
      <button type="submit" class="btn btn-primary" value="Create">Create</button>
    </form>
  </div>
{% endblock %}

src/templates/teachers/delete_teacher.html
{% extends "core/index.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <h3 style="font-size: 10mm; font-family: monospace">
        Do you want to delete teacher "{{ teacher.first_name }} {{ teacher.last_name }}"?
    </h3>
    <button type="submit" class="btn btn-outline-danger" value="Delete">Delete</button>
  </form>
{% endblock %}

src/templates/teachers/teachers_list.html
{% extends "core/index.html" %}

{% block content %}
  <form>
    {% csrf_token %}
    <div class="input-group mb-3" style="width: 100mm">
      <span class="input-group-text" id="inputGroup-sizing-default" style="background: #3A3B3C; color: white">First name:</span>
      <input type="text" id="first_name" name="first_name" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
    </div>
    <div class="input-group mb-3" style="width: 100mm">
      <span class="input-group-text" id="inputGroup-sizing-default" style="background: #3A3B3C; color: white">Last name:</span>
      <input type="text" id="last_name" name="last_name" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
    </div>
    <div class="input-group mb-3" style="width: 100mm">
      <span class="input-group-text" id="inputGroup-sizing-default" style="background: #3A3B3C; color: white">Search Text:</span>
      <input type="text" id="search_text" name="search_text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
    </div>
    <div style="width: 100mm">
      <button type="submit" value="Submit" class="btn btn-primary">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
        </svg>
        Search
      </button>
    </div>
  </form>

  <div style="align-content: start">
    <a type="button" class="btn btn-outline-info"
       href={% url "teachers:create_teacher" %}><b>Add Teacher</b></a>
  </div>
  <hr>
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th scope="col">Avatar</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Salary</th>
        <th scope="col">Birth Day</th>
        <th scope="col">Department</th>
        <th scope="col">Groups</th>
        <th scope="col">Update</th>
        <th scope="col">Remove</th>
      </tr>
    </thead>
    <tbody>
      {% for teacher in teacher_list %}
        <tr>
          <th scope="row"><img src="{{ teacher.avatar.url }}" class="rounded-circle"
                               style="height: 5em; width: 5em; object-fit: cover" alt="None"></th>
          <td>{{ teacher.first_name }}</td>
          <td>{{ teacher.last_name }}</td>
          <td>{{ teacher.email }}</td>
          <td>{{ teacher.salary }}$</td>
          <td>{{ teacher.birth_day }}</td>
          <td>{{ teacher.department }}</td>
          <td>
            {% for group in teacher.groups.all %}
              <a type="button" class="btn btn-outline-info" href={% url "groups:group_info" group.uuid %}>
                  <b>{{ group.title }}</b>
              </a>
            {% endfor %}
          </td>
          <td>
            <a type="button" class="btn btn-outline-warning"
               href={% url "teachers:update_teacher" teacher.uuid %}><b>Edit</b></a>
          </td>
          <td>
            <a type="button" class="btn btn-outline-danger"
               href={% url "teachers:delete_teacher" teacher.uuid %}><b>Delete</b></a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

src/templates/teachers/update_teacher.html
{% extends "core/index.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <div>
    <form method="POST" style="width: 65mm; align-content: center; margin: auto">
      {% csrf_token %}
      {{ form|crispy }}
      <br>
      <button type="submit" class="btn btn-primary" value="Update">Update</button>
    </form>
  </div>
{% endblock %}