src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import NotFoundView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("core/", include("core.urls")),
    path("students/", include("students.urls")),
    path("groups/", include("groups.urls")),
    path("teachers/", include("teachers.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = NotFoundView.as_view()

src/core/urls.py
from django.urls import path

from core.views import IndexView, UserLoginView, UserLogoutView, UserRegistrationView, ActivateUser, UserProfileView

appname = "core"


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("registration/", UserRegistrationView.as_view(), name="registration"),
    path("profile/<int:pk>", UserProfileView.as_view(), name="user_profile"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
]

src/groups/urls.py
from django.contrib import admin  # NOQA
from django.urls import path

from groups.views import CreateGroupView, UpdateGroupView, DeleteGroupView, GetGroupsView, GetGroupInfoView

app_name = "groups"

urlpatterns = [
    path("", GetGroupsView.as_view(), name="groups_list"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<uuid:uuid>", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<uuid:uuid>", DeleteGroupView.as_view(), name="delete_group"),
    path("info/<uuid:uuid>", GetGroupInfoView.as_view(), name="group_info"),
]

src/students/urls.py
from django.urls import path

from students.views import CreateStudentView, UpdateStudentView, DeleteStudentView, GetStudentsView

app_name = "students"

urlpatterns = [
    path("", GetStudentsView.as_view(), name="students_list"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:uuid>", UpdateStudentView.as_view(), name="update_students"),
    path("delete/<uuid:uuid>", DeleteStudentView.as_view(), name="delete_student"),
]

src/teachers/urls.py
from django.urls import path

from teachers.views import CreateTeacherView, UpdateTeacherView, DeleteTeacherView, GetTeachersView

app_name = "teachers"

urlpatterns = [
    path("", GetTeachersView.as_view(), name="teachers_list"),
    path("create/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update/<uuid:uuid>", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<uuid:uuid>", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/core/models.py
import pycountry
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.mail import send_mail
from django.utils import timezone

from django.utils.translation import gettext_lazy as _
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from core.managers import CustomerManager

SEX_CHOICES = (
    ("Male", "Male"),
    ("Female", "Female"),
    ("Undefined", "I don't want to tell"),
)

STATUS_CHOICES = (
    ("Student", "Student"),
    ("Teacher", "Teacher"),
    ("Mentor", "Mentor"),
)

COUNTRY_CHOICES = [(f"{country.name}", f"{country.name}") for country in pycountry.countries]


class Customer(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_("Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    last_name = models.CharField(_("last name"), max_length=150, blank=True)
    email = models.EmailField(_("email address"), blank=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. " "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    avatar = models.ImageField(_("avatar"), upload_to="static/media/profile_avatars/")
    phone_number = PhoneNumberField(null=True)
    location = models.CharField(_("location"), max_length=44, choices=COUNTRY_CHOICES, default="Undefined")
    birth_date = models.DateField(_("birth date"), null=True)
    sex = models.CharField(_("sex"), max_length=9, choices=SEX_CHOICES, default="Undefined")
    status = models.CharField(_("status"), max_length=7, choices=STATUS_CHOICES, default="Student")

    objects = CustomerManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    class Meta:
        verbose_name = _("customer")
        verbose_name_plural = _("customers")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def get_working_time(self):
        return timezone.now() - self.date_joined

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        return f"{self.username} [{self.pk}]"

src/core/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "email", "first_name", "last_name", "password1", "password2")

src/core/views.py
from django.contrib.auth import login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.views.generic import TemplateView, CreateView, RedirectView, DetailView

from core.forms import UserRegistrationForm
from core.models import Customer
from core.services.emails import send_registration_email
from core.utils.token_generator import TokenGenerator


class IndexView(TemplateView):
    template_name = "core/index.html"
    http_method_names = ["get"]


class NotFoundView(TemplateView):
    template_name = "core/404.html"


class UserLoginView(LoginView):
    ...


class UserLogoutView(LogoutView):
    ...


class UserRegistrationView(CreateView):
    template_name = "registration/registration.html"
    form_class = UserRegistrationForm
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_active = False
        self.object.save()

        send_registration_email(self.request, self.object)

        return super().form_valid(form)


class ActivateUser(RedirectView):
    url = reverse_lazy("index")

    def get(self, request, uuid64, token, *args, **kwargs):
        try:
            pk = force_str(urlsafe_base64_decode(uuid64))
            current_user = get_user_model().objects.get(pk=pk)
        except (ValueError, get_user_model().DoesNotExist, TypeError):
            return HttpResponse("Wrong data!!!")

        if current_user and TokenGenerator().check_token(current_user, token):
            current_user.is_active = True
            current_user.save()

            login(request, current_user)

            return super().get(request, *args, **kwargs)

        return HttpResponse("Wrong data!!!")


class UserProfileView(LoginRequiredMixin, DetailView):
    template_name = "core/user_profile.html"
    pk_url_kwarg = "pk"
    queryset = Customer.objects.all()

src/templates/core/index.html
{% load static %}

<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Django LMS</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/cover/">




    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static "css/cover.css" %}" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-bg-dark">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="mb-auto">
        <div>
          <h3 class="float-md-start mb-0"><a class="nav-link fw-bold py-1 px-0" aria-current="page" href={% url "index" %}>Django LMS</a></h3>
          <nav class="nav nav-masthead justify-content-center float-md-end">
            <a class="nav-link fw-bold py-1 px-0" style="margin-right: 3mm; color: white; font-size: 5mm" href={% url "groups:groups_list" %}>Groups</a>
            <a class="nav-link fw-bold py-1 px-0" style="margin-right: 3mm; color: white; font-size: 5mm" href={% url "students:students_list" %}>Students</a>
            <a class="nav-link fw-bold py-1 px-0" style="margin-right: 3mm; color: white; font-size: 5mm" href={% url "teachers:teachers_list" %}>Teachers</a>
            <div class="dropdown text-center">
              <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle show" data-bs-toggle="dropdown" aria-expanded="true">
                {% if user.avatar %}
                  <img src="{{ user.avatar.url }}" class="rounded-circle" width="32" height="32" style="object-fit: cover" alt="menu">
                {% else %}
                  <img src="https://ps.w.org/user-avatar-reloaded/assets/icon-128x128.png" alt="menu" width="32" height="32" class="rounded-circle">
                {% endif %}
              </a>
              <ul class="dropdown-menu text-small" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(0px, 34.4px, 0px);" data-popper-placement="bottom-start">
                {% if user.is_authenticated %}
                  <li><p class="dropdown-item-text">{{ user.username }}</p></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url "user_profile" user.pk %}">Profile</a></li>
                  <li><a class="dropdown-item" href="#">Change password</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url "logout" %}">Logout</a></li>
                {% else %}
                  <li><a class="dropdown-item" href="{% url "login" %}">Login</a></li>
                  <li><a class="dropdown-item" href="{% url "registration" %}">Registration</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Change password</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url "social:begin" "github" %}">Login via GitHub</a></li>
                  <li><a class="dropdown-item" href="{% url "social:begin" "google-oauth2" %}">Login via Google</a></li>
                {% endif %}
              </ul>
            </div>
          </nav>
        </div>
      </header>
      <main class="px-3">
        {% block content %}
          <img src="{% static "media/core_media/lms-technologies-png.png" %}" class="img-thumbnail" alt="LMS image" />
          <h1>Learning Management System</h1>
          <p class="lead">Keep control of your course.</p>
          <p class="lead">
          <a href="https://en.wikipedia.org/wiki/Learning_management_system" class="btn btn-lg btn-light fw-bold border-white bg-white">Learn more</a>
          </p>
          {% endblock %}
      </main>

      <footer class="mt-auto text-white-50">
        <hr>
        <p>Django LMS [ <a href="https://gitlab.com/igorsamarsky/lms_2022" class="text-white">Code</a> ], by <a href="https://instagram.com/_igor_samara_" class="text-white">Ihor Samarskyi</a>.</p>
      </footer>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/core/user_profile.html
{% extends "core/index.html" %}


{% block content %}
    <div style="font-family: fantasy; letter-spacing: 1px;">
        <img src="{{ customer.avatar.url }}" class="rounded-circle"
             style="height: 5em; width: 5em; object-fit: cover" alt="avatar">
        <h2>Username: {{ customer.username }};</h2>
        <h4>Name: {{ customer.first_name }};</h4>
        <h4>Surname: {{ customer.last_name }};</h4>
        <h4>Email: {{ customer.email }};</h4>
        <h4>Phone Number: {{ customer.phone_number }};</h4>
        <h4>Country: {{ customer.location }};</h4>
        <h4>Birth Date: {{ customer.birth_date }};</h4>
        <h4>Sex: {{ customer.sex }};</h4>
        <h4>Status: {{ customer.status }};</h4>
    </div>
{% endblock %}