src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import NotFoundView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("core/", include("core.urls")),
    path("students/", include("students.urls")),
    path("groups/", include("groups.urls")),
    path("teachers/", include("teachers.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = NotFoundView.as_view()

src/core/urls.py
from django.urls import path

from core.views import IndexView, UserLoginView, UserLogoutView, UserRegistrationView, ActivateUser, UserProfileView

appname = "core"


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("registration/", UserRegistrationView.as_view(), name="registration"),
    path("profile/<int:pk>", UserProfileView.as_view(), name="user_profile"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
]

src/groups/urls.py
from django.contrib import admin  # NOQA
from django.urls import path

from groups.views import CreateGroupView, UpdateGroupView, DeleteGroupView, GetGroupsView, GetGroupInfoView

app_name = "groups"

urlpatterns = [
    path("", GetGroupsView.as_view(), name="groups_list"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<uuid:uuid>", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<uuid:uuid>", DeleteGroupView.as_view(), name="delete_group"),
    path("info/<uuid:uuid>", GetGroupInfoView.as_view(), name="group_info"),
]

src/groups/models.py
import random
from uuid import uuid4

from django.db import models
from faker import Faker

from core.utils.validators import gpa_validator, median_age_validator


class Group(models.Model):
    uuid = models.UUIDField(primary_key=True, editable=False, default=uuid4, unique=True, db_index=True)
    title = models.CharField(max_length=120, null=True)
    department = models.CharField(max_length=120, null=True)
    students_count = models.PositiveIntegerField(default=0, null=True)
    gpa = models.FloatField(default=0, null=True, validators=[gpa_validator])
    median_age = models.FloatField(default=0, null=True, validators=[median_age_validator])
    start_date = models.DateField(null=True)

    def __str__(self):
        return f"{self.title} [{self.department}] ({self.pk})"

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for _ in range(count):
            department = faker.job()
            start_date = faker.date_time_between(start_date="-4y")
            start_year = start_date[4]
            cls.objects.create(
                title=f"{department[0]}-{start_year}",
                department=department,
                students_count=faker.random.randint(1, 50),
                gpa=round(random.uniform(1, 5), 2),
                median_age=round(random.uniform(18, 30), 2),
                start_date=start_date,
            )

src/groups/forms.py
from django.forms import ModelForm

from groups.models import Group


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = "__all__"

src/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView

from core.utils.helpers import objects_search
from groups.forms import GroupForm
from groups.models import Group


class GetGroupInfoView(LoginRequiredMixin, DetailView):
    template_name = "groups/group_info.html"
    pk_url_kwarg = "uuid"
    queryset = Group.objects.all()


class GetGroupsView(LoginRequiredMixin, ListView):
    template_name = "groups/groups_list.html"
    model = Group

    def get_groups(self):
        search_fields = ["title"]
        return objects_search(self.request.GET, self.model, search_fields)

    def get_queryset(self):
        return self.get_groups()


class CreateGroupView(LoginRequiredMixin, CreateView):
    template_name = "groups/create_group.html"
    form_class = GroupForm
    success_url = reverse_lazy("groups:groups_list")


class UpdateGroupView(LoginRequiredMixin, UpdateView):
    template_name = "groups/update_group.html"
    form_class = GroupForm
    success_url = reverse_lazy("groups:groups_list")
    pk_url_kwarg = "uuid"
    queryset = Group.objects.all()


class DeleteGroupView(LoginRequiredMixin, DeleteView):
    template_name = "groups/delete_group.html"
    model = Group
    success_url = reverse_lazy("groups:groups_list")
    pk_url_kwarg = "uuid"
    queryset = Group.objects.all()

src/templates/groups/create_group.html
{% extends "core/index.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <div>
    <form method="POST" style="width: 65mm; align-content: center; margin: auto">
      {% csrf_token %}
      {{ form|crispy }}
      <br>
      <button type="submit" class="btn btn-primary" value="Create">Create</button>
    </form>
  </div>
{% endblock %}

src/templates/groups/delete_group.html
{% extends "core/index.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <h3 style="font-size: 10mm; font-family: monospace">
        Do you want to delete group "{{ group.title }}"?
    </h3>
    <button type="submit" class="btn btn-outline-danger" value="Delete">Delete</button>
  </form>
{% endblock %}

src/templates/groups/group_info.html
{% extends "core/index.html" %}

{% block content %}
  <div style="font-family: fantasy; letter-spacing: 1px">
    <h1>Group Info:</h1>
    <h3>Title: {{ group.title }};</h3>
    <h3>Department: {{ group.department }};</h3>
    <h3>Count of students: {{ group.students_count }};</h3>
    <h3>GPA: {{ group.gpa }};</h3>
    <h3>Median age of students: {{ group.median_age }};</h3>
    <h3>Start date: {{ group.start_date }};</h3>
    <h3>
      Teachers:
      {% for teacher in group.teachers.all %}
        {{ teacher.first_name }} {{ teacher.last_name }};
      {% endfor %}c
    </h3>
    <h3>
        Students:
        {% for student in group.students.all %}
            {{ student.first_name }} {{ student.last_name }};
        {% endfor %}
    </h3>
  </div>
{% endblock %}

src/templates/groups/groups_list.html
{% extends "core/index.html" %}

{% block content %}
  <form>
    {% csrf_token %}
    <div class="input-group mb-3" style="width: 100mm">
      <span class="input-group-text" id="inputGroup-sizing-default" style="background: #3A3B3C; color: white">Title:</span>
      <input type="text" id="title" name="title" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
    </div>
    <div class="input-group mb-3" style="width: 100mm">
      <span class="input-group-text" id="inputGroup-sizing-default" style="background: #3A3B3C; color: white">Search Text:</span>
      <input type="text" id="search_text" name="search_text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
    </div>
    <div style="width: 100mm">
      <button type="submit" value="Submit" class="btn btn-primary">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
        </svg>
        Search
      </button>
    </div>
  </form>

  <div style="align-content: start">
    <a type="button" class="btn btn-outline-info"
       href={% url "groups:create_group" %}><b>Add Group</b></a>
  </div>
  <hr>
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Department</th>
        <th scope="col">Students Count</th>
        <th scope="col">GPA</th>
        <th scope="col">Median Age</th>
        <th scope="col">Start Date</th>
        <th scope="col">Update</th>
        <th scope="col">Remove</th>
      </tr>
    </thead>
    <tbody>
      {% for group in group_list %}
        <tr>
          <th scope="row">{{ group.title }}</th>
          <td>{{ group.department }}</td>
          <td>{{ group.students_count }}</td>
          <td>{{ group.gpa }}</td>
          <td>{{ group.median_age }}</td>
          <td>{{ group.start_date }}</td>
          <td>
            <a type="button" class="btn btn-outline-warning"
               href={% url "groups:update_group" group.uuid %}><b>Edit</b></a>
          </td>
          <td>
            <a type="button" class="btn btn-outline-danger"
               href={% url "groups:delete_group" group.uuid %}><b>Delete</b></a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

src/templates/groups/update_group.html
{% extends "core/index.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <div>
    <form method="POST" style="width: 65mm; align-content: center; margin: auto">
      {% csrf_token %}
      {{ form|crispy }}
      <br>
      <button type="submit" class="btn btn-primary" value="Update">Update</button>
    </form>
  </div>
{% endblock %}